// ============================================================
// SEQUENCE-COACH EDGE FUNCTION
// ============================================================
// OpenAI-only. Lets a rep iterate on a draft generated by
// sequence-generator. Reads the existing draft + rep instruction
// ("make this more concise", "less salesy", "add a stat about
// X"), returns a refined version. The function does NOT auto-
// apply — the caller (UI) shows the proposed body and lets the
// user accept / discard. Each accepted iteration is appended
// to prospect_sequence_drafts.iteration_history for audit.
//
// Inputs (POST JSON):
//   { draft_id: uuid, instruction: string }
//
// Output:
//   { success, draft: { subject, body, method }, proposal:
//     { subject, body }, iteration: { ts, model, prompt } }
// ============================================================
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { requireUser, corsHeaders, jsonResponse } from "../_shared/devGuard.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY") ?? "";
const MODEL = Deno.env.get("SEQUENCE_COACH_MODEL") ?? "gpt-4.1-mini";

const SYSTEM_PROMPT = `You refine outreach drafts based on the rep's instruction. The rep gives you the existing draft + a one-line ask ("make it shorter", "more direct", "lead with the funding round", etc.). Return ONE refined version.

Hard rules:
  • Stay in the same channel (email / linkedin / phone script / internal task note).
  • Keep the prospect's name + company unchanged.
  • Keep word count within ±20% of the original unless the instruction explicitly asks for shorter / longer.
  • For email, preserve the subject if it still fits the body; rewrite the subject only if the rep asked.
  • For phone scripts, keep second person and the "Hey {first_name}, this is {sender}" opener.
  • Never invent firmographic numbers (revenue, headcount, deal size).

Output JSON ONLY (no prose, no fences):

{ "subject": "…" or null, "body": "…" }`;

interface CoachBody {
  draft_id: string;
  instruction: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const guard = await requireUser(req);
  if (!guard.ok) return guard.response;
  const { userId } = guard;

  if (!OPENAI_API_KEY) {
    return jsonResponse({ success: false, error: "OPENAI_API_KEY not configured" }, 500);
  }

  const sb = createClient(SUPABASE_URL, SERVICE_KEY);

  let body: CoachBody;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ success: false, error: "Invalid JSON body" }, 400);
  }

  const draftId = body.draft_id;
  const instruction = (body.instruction || "").trim();
  if (!draftId) return jsonResponse({ success: false, error: "draft_id required" }, 400);
  if (!instruction) return jsonResponse({ success: false, error: "instruction required" }, 400);
  if (instruction.length > 1000) return jsonResponse({ success: false, error: "instruction too long" }, 400);

  // ─── Load draft + scope check ────────────────────────────
  const { data: draft } = await sb
    .from("prospect_sequence_drafts")
    .select("*, enrollment:prospect_sequence_enrollments(deal_id, contact_id, property_id)")
    .eq("id", draftId)
    .maybeSingle();
  if (!draft) return jsonResponse({ success: false, error: "draft not found" }, 404);

  // Verify the rep belongs to the same property as the draft.
  const { data: profile } = await sb
    .from("profiles").select("property_id, role")
    .eq("id", userId).maybeSingle();
  if (profile?.role !== "developer" && profile?.property_id !== draft.property_id) {
    return jsonResponse({ success: false, error: "forbidden" }, 403);
  }

  // ─── Build prompt + call OpenAI ──────────────────────────
  const userPrompt = `Channel: ${draft.method}
${draft.subject ? `Current subject: ${draft.subject}\n` : ""}Current body:
"""
${draft.body}
"""

Rep's instruction: ${instruction}

Return the refined draft as JSON only.`;

  let aiRes: Response;
  try {
    aiRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${OPENAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.4,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
      }),
    });
  } catch (err) {
    return jsonResponse({ success: false, error: `openai_request_failed: ${String(err)}` }, 502);
  }

  if (!aiRes.ok) {
    const errText = await aiRes.text();
    return jsonResponse({
      success: false,
      error: `openai_${aiRes.status}`,
      details: errText.slice(0, 500),
    }, 502);
  }

  const aiData = await aiRes.json();
  const raw = aiData.choices?.[0]?.message?.content || "{}";
  let parsed: { subject?: string | null; body?: string };
  try {
    parsed = JSON.parse(raw);
  } catch {
    return jsonResponse({ success: false, error: "openai_returned_non_json", raw: raw.slice(0, 500) }, 502);
  }
  if (!parsed.body) {
    return jsonResponse({ success: false, error: "openai_missing_body", raw: raw.slice(0, 500) }, 502);
  }

  // ─── Append to iteration_history (no auto-apply) ────────
  const iter = {
    ts: new Date().toISOString(),
    model: MODEL,
    instruction,
    proposal: { subject: parsed.subject ?? null, body: parsed.body },
    by: userId,
  };
  const newHistory = Array.isArray(draft.iteration_history)
    ? [...draft.iteration_history, iter]
    : [iter];
  await sb.from("prospect_sequence_drafts")
    .update({ iteration_history: newHistory })
    .eq("id", draftId);

  return jsonResponse({
    success: true,
    draft: {
      id: draft.id,
      subject: draft.subject,
      body: draft.body,
      method: draft.method,
    },
    proposal: {
      subject: parsed.subject ?? null,
      body: parsed.body,
    },
    iteration: iter,
  });
});
