included:
  - Rally
  - Packages

excluded:
  - "*/Tests/*"
  - DerivedData
  - .build
  - Pods

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - db
    - x
    - y
    - i
    - j

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

nesting:
  type_level: 3
  function_level: 3

reporter: xcode

custom_rules:
  rally_no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    message: "Use OSLog (Logger) instead of print()."
    severity: warning
  rally_no_force_unwrap:
    name: "No force unwraps"
    regex: "\\w+!"
    match_kinds:
      - identifier
    message: "Avoid force unwrapping. Use optional binding or nil coalescing."
    severity: warning
