import { supabase } from '@/lib/supabase'

/**
 * CRUD for archived Claude Code repair prompts generated by the
 * AutoQA engine.
 */

export const PATTERNS = [
  { key: 'rls_write_failures', label: 'RLS write failures', severity: 'high' },
  { key: 'check_constraint',   label: 'CHECK constraint',   severity: 'high' },
  { key: 'missing_column',     label: 'Missing columns',    severity: 'critical' },
  { key: 'missing_table',      label: 'Missing tables',     severity: 'critical' },
  { key: 'edge_fn_failures',   label: 'Edge fn failures',   severity: 'high' },
  { key: 'flaky_tests',        label: 'Flaky tests',        severity: 'medium' },
  { key: 'upload_failures',    label: 'Upload failures',    severity: 'medium' },
  { key: 'custom',             label: 'Custom',             severity: 'medium' },
]

export const STATUSES = ['new', 'copied', 'applied', 'archived', 'dismissed']

export async function createPrompt(fields, userId, qaReportId = null) {
  const { data, error } = await supabase
    .from('qa_repair_prompts')
    .insert({
      ...fields,
      created_by: userId,
      qa_report_id: qaReportId,
    })
    .select()
    .single()
  return error ? { success: false, error: error.message } : { success: true, prompt: data }
}

export async function listPrompts({ status, pattern, limit = 200 } = {}) {
  let q = supabase
    .from('qa_repair_prompts')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(limit)
  if (status && status !== 'all') q = q.eq('status', status)
  if (pattern && pattern !== 'all') q = q.eq('pattern_detected', pattern)
  const { data, error } = await q
  return error ? { prompts: [], error: error.message } : { prompts: data || [] }
}

export async function getPrompt(id) {
  const { data, error } = await supabase
    .from('qa_repair_prompts')
    .select('*')
    .eq('id', id)
    .maybeSingle()
  return error ? { prompt: null, error: error.message } : { prompt: data }
}

export async function updatePrompt(id, patch) {
  const { error } = await supabase
    .from('qa_repair_prompts')
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq('id', id)
  return error ? { success: false, error: error.message } : { success: true }
}

export async function markCopied(id) {
  return updatePrompt(id, { status: 'copied', copied_at: new Date().toISOString() })
}

export async function markApplied(id, notes) {
  return updatePrompt(id, { status: 'applied', applied_at: new Date().toISOString(), notes })
}

export async function archivePrompt(id) {
  return updatePrompt(id, { status: 'archived' })
}

export async function dismissPrompt(id) {
  return updatePrompt(id, { status: 'dismissed' })
}

export async function deletePrompt(id) {
  const { error } = await supabase.from('qa_repair_prompts').delete().eq('id', id)
  return error ? { success: false, error: error.message } : { success: true }
}

/**
 * Bulk-save a set of patterns detected by the engine as archived
 * prompts. Called from the AutoQAEngine control panel when the
 * user clicks "Save prompts to archive".
 */
export async function bulkSavePatterns(patterns, userId, qaReportId = null) {
  const rows = patterns.map(p => ({
    qa_report_id: qaReportId,
    title: p.title,
    summary: p.summary,
    pattern_detected: p.pattern_detected,
    severity: p.severity,
    prompt_text: p.prompt_text,
    evidence: p.evidence || {},
    status: 'new',
    created_by: userId,
  }))
  if (rows.length === 0) return { success: true, saved: 0 }
  const { data, error } = await supabase
    .from('qa_repair_prompts')
    .insert(rows)
    .select()
  return error
    ? { success: false, error: error.message }
    : { success: true, saved: data?.length || 0, prompts: data }
}
