import { useEffect, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '@/hooks/useAuth'
import { useToast } from '@/components/Toast'
import * as promptService from '@/services/qaRepairPromptService'

/**
 * /app/developer/repair-prompts — archive of every Claude Code
 * repair prompt ever generated by the AutoQA engine. Filter,
 * search, copy to clipboard, mark as applied/archived.
 */
export default function QARepairPrompts() {
  const { profile } = useAuth()
  const { toast } = useToast()
  const [prompts, setPrompts] = useState([])
  const [loading, setLoading] = useState(true)
  const [filters, setFilters] = useState({ status: 'all', pattern: 'all' })
  const [expanded, setExpanded] = useState(null)

  if (profile && profile.role !== 'developer') return <Navigate to="/app" replace />

  useEffect(() => { reload() }, [filters])

  async function reload() {
    setLoading(true)
    const { prompts } = await promptService.listPrompts(filters)
    setPrompts(prompts)
    setLoading(false)
  }

  async function copyPrompt(p) {
    try {
      await navigator.clipboard.writeText(p.prompt_text)
      await promptService.markCopied(p.id)
      toast({ title: 'Copied', description: 'Paste into Claude Code', type: 'success' })
      reload()
    } catch {
      toast({ title: 'Copy failed', type: 'error' })
    }
  }

  async function markApplied(p) {
    const notes = prompt('Optional note about the fix:') || null
    await promptService.markApplied(p.id, notes)
    toast({ title: 'Marked as applied', type: 'success' })
    reload()
  }

  async function archive(p) {
    await promptService.archivePrompt(p.id)
    reload()
  }

  async function dismiss(p) {
    await promptService.dismissPrompt(p.id)
    reload()
  }

  async function remove(p) {
    if (!confirm('Delete this prompt permanently?')) return
    await promptService.deletePrompt(p.id)
    reload()
  }

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 space-y-5">
      <header className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <Link to="/app/developer" className="text-[10px] text-text-muted hover:text-accent">← Dev Tools</Link>
          <h1 className="text-xl sm:text-2xl font-semibold mt-1">AI Repair Prompts</h1>
          <p className="text-[11px] text-text-muted">Archived Claude Code prompts generated by the QA engine.</p>
        </div>
        <Link
          to="/app/developer/auto-qa"
          className="text-xs bg-accent text-bg-primary px-3 py-1.5 rounded font-semibold"
        >
          Run QA pass →
        </Link>
      </header>

      <div className="flex items-center gap-2 flex-wrap border-b border-border pb-3">
        <select
          value={filters.status}
          onChange={e => setFilters({ ...filters, status: e.target.value })}
          className="bg-bg-card border border-border rounded px-2 py-1.5 text-xs"
        >
          <option value="all">All statuses</option>
          {promptService.STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
        </select>
        <select
          value={filters.pattern}
          onChange={e => setFilters({ ...filters, pattern: e.target.value })}
          className="bg-bg-card border border-border rounded px-2 py-1.5 text-xs"
        >
          <option value="all">All patterns</option>
          {promptService.PATTERNS.map(p => <option key={p.key} value={p.key}>{p.label}</option>)}
        </select>
      </div>

      {loading && <div className="text-xs text-text-muted py-4 text-center">Loading…</div>}

      {!loading && prompts.length === 0 && (
        <div className="bg-bg-card border border-border rounded-lg p-8 text-center text-xs text-text-muted">
          <div>No prompts match these filters.</div>
          <Link to="/app/developer/auto-qa" className="text-accent hover:underline mt-2 inline-block">
            Run a QA pass to generate some
          </Link>
        </div>
      )}

      {prompts.map(p => {
        const isExpanded = expanded === p.id
        const sevColor = p.severity === 'critical' ? 'danger'
          : p.severity === 'high' ? 'warning'
          : 'accent'
        const statusColor = p.status === 'applied' ? 'success'
          : p.status === 'copied' ? 'accent'
          : p.status === 'dismissed' ? 'muted'
          : 'text-text-secondary'
        return (
          <div key={p.id} className="bg-bg-card border border-border rounded-lg overflow-hidden">
            <div className="p-4 space-y-2">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <span className={`text-[9px] font-mono px-1.5 py-0.5 rounded bg-${sevColor}/15 text-${sevColor}`}>
                      {p.severity}
                    </span>
                    <span className="text-[9px] font-mono text-text-muted">{p.pattern_detected}</span>
                    <span className={`text-[9px] font-mono ml-auto text-${statusColor === 'success' ? 'success' : statusColor === 'accent' ? 'accent' : 'text-muted'}`}>
                      {p.status}
                    </span>
                  </div>
                  <h3 className="text-sm font-semibold">{p.title}</h3>
                  {p.summary && <p className="text-[11px] text-text-secondary mt-1">{p.summary}</p>}
                  <div className="text-[10px] text-text-muted mt-1">
                    {new Date(p.created_at).toLocaleString()}
                    {p.copied_at && ` · copied ${new Date(p.copied_at).toLocaleString()}`}
                    {p.applied_at && ` · applied ${new Date(p.applied_at).toLocaleString()}`}
                  </div>
                  {p.notes && (
                    <div className="mt-2 text-[11px] bg-success/5 border-l-2 border-success pl-2 py-1">
                      <span className="text-success font-mono text-[9px] uppercase">Note</span>
                      <div className="text-text-secondary mt-0.5">{p.notes}</div>
                    </div>
                  )}
                </div>
              </div>

              <div className="flex gap-1 flex-wrap pt-2 border-t border-border">
                <button onClick={() => copyPrompt(p)} className="text-[10px] bg-accent text-bg-primary px-2 py-1 rounded font-semibold">
                  Copy prompt
                </button>
                <button onClick={() => setExpanded(isExpanded ? null : p.id)} className="text-[10px] border border-border px-2 py-1 rounded text-text-secondary">
                  {isExpanded ? 'Hide' : 'Show'}
                </button>
                {p.status !== 'applied' && (
                  <button onClick={() => markApplied(p)} className="text-[10px] border border-success/30 text-success px-2 py-1 rounded">
                    Mark applied
                  </button>
                )}
                {p.status !== 'archived' && (
                  <button onClick={() => archive(p)} className="text-[10px] border border-border text-text-secondary px-2 py-1 rounded">
                    Archive
                  </button>
                )}
                {p.status !== 'dismissed' && (
                  <button onClick={() => dismiss(p)} className="text-[10px] border border-border text-text-muted px-2 py-1 rounded">
                    Dismiss
                  </button>
                )}
                <button onClick={() => remove(p)} className="text-[10px] border border-danger/30 text-danger px-2 py-1 rounded ml-auto">
                  Delete
                </button>
              </div>

              {isExpanded && (
                <pre className="mt-2 bg-bg-surface border border-border rounded p-3 text-[10px] text-text-secondary overflow-x-auto whitespace-pre-wrap font-mono max-h-96">
                  {p.prompt_text}
                </pre>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}
