-- ============================================================
-- MIGRATION 062 — DIGEST MANAGEMENT SYSTEM
-- ============================================================
-- "The Digest by Loud Legacy Ventures" — monthly editorial
-- newsletter/article living at loud-legacy.com/digest.
--
-- Deliberately does NOT create a new subscribers table — the
-- existing email_subscribers table from migration 054 already
-- has email, first/last name, industry, status, unsubscribe_token,
-- and tags. Digest subscribers are just email_subscribers rows
-- with 'digest' in their tags array.
--
-- Deliberately does NOT create a new campaigns table — on publish,
-- a row is written to email_campaigns (from migration 054) with
-- the article rendered into the branded HTML email template, and
-- the existing email-marketing-send edge function delivers it.
--
-- What this migration ADDS:
--   - digest_issues:           editorial content (title, body md, status)
--   - digest_issue_images:     image library scoped to issues
--   - digest_signup_events:    audit log of signups from landing page
-- ============================================================

-- Drop the CHECK constraint one more time in case the DB is still
-- stuck on the migration 045 version. Idempotent. See migration
-- 058 for the permanent fix.
alter table feature_flags drop constraint if exists feature_flags_module_check;

-- ========================
-- 1. DIGEST ISSUES
-- ========================
create table if not exists digest_issues (
  id uuid primary key default gen_random_uuid(),

  -- Core content
  slug text not null unique,       -- URL-safe: e.g. "february-2026-real-estate-trends"
  title text not null,
  subtitle text,
  author text default 'Loud Legacy Ventures',

  -- Body — stored as Markdown, rendered to HTML at display time
  body_markdown text not null default '',

  -- Featured image
  featured_image_url text,
  featured_image_alt text,

  -- Taxonomy
  industry text,                   -- 'real_estate' | 'sports' | 'marketing' | 'general' | null
  tags text[] default '{}',

  -- Publish lifecycle
  status text not null default 'draft',
    -- 'draft' | 'scheduled' | 'published' | 'archived'
  published_at timestamptz,
  scheduled_for timestamptz,       -- if status='scheduled'

  -- SEO
  meta_title text,                 -- falls back to title
  meta_description text,           -- falls back to subtitle + first 150 chars
  canonical_url text,

  -- Metrics (denormalized from email_campaigns + digest_article_views)
  view_count integer not null default 0,
  email_sends integer not null default 0,
  email_opens integer not null default 0,
  email_clicks integer not null default 0,

  -- Email dispatch link
  email_campaign_id uuid,          -- FK to email_campaigns (nullable before publish)
  send_email_on_publish boolean default true,
  email_sent_at timestamptz,

  -- AI research provenance (when an issue was generated by digest-research)
  ai_researched boolean default false,
  ai_research_prompt text,
  ai_research_citations jsonb default '[]'::jsonb,

  -- Audit
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_digest_issues_status on digest_issues(status);
create index if not exists idx_digest_issues_published on digest_issues(published_at desc) where status = 'published';
create index if not exists idx_digest_issues_scheduled on digest_issues(scheduled_for) where status = 'scheduled';
create index if not exists idx_digest_issues_industry on digest_issues(industry);
create index if not exists idx_digest_issues_slug on digest_issues(slug);

alter table digest_issues enable row level security;

-- Public READ for published issues only — powers the /digest archive
create policy "digest_issues_public_read" on digest_issues
  for select using (status = 'published');

-- Developer WRITES (and also reads drafts) — authoring flow
create policy "digest_issues_developer_write" on digest_issues
  for all using (is_developer())
  with check (is_developer());

-- ========================
-- 2. DIGEST ISSUE IMAGES (image library)
-- ========================
-- Every image uploaded via the editor is tracked here so it can
-- be reused across issues. Storage itself lives in the 'media'
-- bucket (migration 061); this table stores the URL + metadata.
create table if not exists digest_issue_images (
  id uuid primary key default gen_random_uuid(),
  issue_id uuid references digest_issues(id) on delete set null,
  uploaded_by uuid references auth.users(id) on delete set null,

  storage_path text not null,      -- path in media bucket
  public_url text not null,
  original_filename text,
  file_size_bytes integer,
  width integer,
  height integer,

  alt_text text,
  caption text,
  position text default 'inline',  -- 'inline' | 'full_width' | 'featured'

  is_reusable boolean default true, -- if true, appears in the image library picker
  created_at timestamptz not null default now()
);

create index if not exists idx_digest_issue_images_issue on digest_issue_images(issue_id);
create index if not exists idx_digest_issue_images_reusable on digest_issue_images(is_reusable, created_at desc);

alter table digest_issue_images enable row level security;

create policy "digest_images_public_read" on digest_issue_images for select using (true);
create policy "digest_images_developer_write" on digest_issue_images
  for all using (is_developer()) with check (is_developer());

-- ========================
-- 3. DIGEST SIGNUP EVENTS (audit log for landing-page signups)
-- ========================
-- When someone submits the Digest signup form on the landing page,
-- two things happen: (1) an email_subscribers row is created
-- with 'digest' tag, (2) a row lands here for audit/analytics.
-- Keeping this separate from email_subscriber_events so Digest
-- analytics can be queried without cluttering the subscriber
-- events stream.
create table if not exists digest_signup_events (
  id uuid primary key default gen_random_uuid(),
  subscriber_id uuid references email_subscribers(id) on delete set null,
  email text not null,
  first_name text,
  industry_interest text,
  source text default 'landing_page',  -- 'landing_page' | 'article_footer' | 'archive_page'
  user_agent text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamptz not null default now()
);

create index if not exists idx_digest_signup_events_created on digest_signup_events(created_at desc);
create index if not exists idx_digest_signup_events_email on digest_signup_events(lower(email));

alter table digest_signup_events enable row level security;

-- Public can INSERT (landing page signup is unauthenticated)
create policy "digest_signups_public_insert" on digest_signup_events
  for insert with check (true);

-- Developer reads
create policy "digest_signups_developer_read" on digest_signup_events
  for select using (is_developer());

-- ========================
-- 4. DIGEST ARTICLE VIEWS (simple view counter)
-- ========================
-- Lightweight view logging so we can show read counts in the
-- admin panel. Does NOT store PII — just timestamps + issue_id.
create table if not exists digest_article_views (
  id bigserial primary key,
  issue_id uuid not null references digest_issues(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  referrer text,
  utm_source text
);

create index if not exists idx_digest_views_issue on digest_article_views(issue_id, viewed_at desc);

alter table digest_article_views enable row level security;

-- Public INSERT (view tracking is unauthenticated)
create policy "digest_views_public_insert" on digest_article_views
  for insert with check (true);

create policy "digest_views_developer_read" on digest_article_views
  for select using (is_developer());

-- ========================
-- 5. FEATURE FLAG (hidden, developer-only gate)
-- ========================
insert into feature_flags (module, enabled, updated_at)
values ('digest_system', true, now())
on conflict (module) do nothing;

-- ============================================================
-- DONE
-- ============================================================
