import { NextRequest, NextResponse } from "next/server";
import { analyzeImprovementsFromImage } from "@/lib/openai";

export const dynamic = 'force-dynamic';

// Fallback analyses keyed by area
const FALLBACK_ANALYSES: Record<string, {
  overallScore: number;
  condition: string;
  issues: string[];
  improvements: Array<{
    title: string;
    description: string;
    specificChanges: string[];
    estimatedCost: { low: number; high: number };
    potentialROI: number;
    costBasis: string;
    valueRationale: string;
    priority: string;
    timeframe: string;
  }>;
  estimatedValueImpact: number;
}> = {
  "exterior-front": {
    overallScore: 68,
    condition: "fair",
    issues: ["Faded exterior paint", "Dated front door", "Basic landscaping", "Missing house numbers"],
    improvements: [
      { title: "Fresh Exterior Paint", description: "Repaint the front facade with modern neutral colors. A fresh coat of paint is one of the most cost-effective ways to improve curb appeal, which directly influences buyer first impressions and perceived home value.", specificChanges: ["Power wash all exterior surfaces to remove dirt, mildew, and loose paint", "Scrape and sand peeling or flaking paint areas down to solid surface", "Apply exterior primer to all bare wood and repaired areas", "Apply two coats of premium acrylic latex paint in Agreeable Gray or Alabaster (Sherwin-Williams)", "Paint all trim, fascia, and soffits in crisp white for contrast", "Caulk all gaps around windows, doors, and trim joints"], estimatedCost: { low: 3500, high: 6000 }, potentialROI: 150, costBasis: "Based on average exterior painting costs of $2-4 per square foot for a typical 1,500 sqft facade, including prep, primer, two coats of premium paint, and labor at $35-50/hr.", valueRationale: "National Association of Realtors data shows exterior paint recovery rate of 150% at resale. Fresh exterior paint is consistently ranked in the top 3 ROI home improvements by real estate professionals.", priority: "high", timeframe: "3-5 days" },
      { title: "New Front Door", description: "Replace with a modern fiberglass or steel entry door with decorative glass. The front door is the focal point of curb appeal and sets buyer expectations for the rest of the home.", specificChanges: ["Remove existing front door and frame", "Install pre-hung fiberglass entry door with decorative glass sidelite or transom", "Add new brushed nickel or matte black handleset with deadbolt (Schlage or Kwikset)", "Install new weatherstripping and threshold for energy efficiency", "Paint door a bold accent color (navy blue, black, or deep red) to pop against the facade", "Add new house numbers in modern font mounted beside the door"], estimatedCost: { low: 1500, high: 3000 }, potentialROI: 200, costBasis: "Fiberglass or steel entry door ($800-$2,000), decorative glass insert ($200-$500), new hardware and lockset ($100-$300), professional installation ($400-$600).", valueRationale: "Remodeling Magazine Cost vs. Value report consistently ranks front door replacement as the #1 ROI project, recovering 90-100% or more of cost. A 200% ROI reflects the outsized impact on first impressions.", priority: "high", timeframe: "1 day" },
      { title: "Landscape Enhancement", description: "Add foundation plantings, mulch beds, and seasonal flowers to boost curb appeal. Landscaping creates a welcoming first impression that makes buyers emotionally invested before they enter the home.", specificChanges: ["Plant 5-7 evergreen foundation shrubs (boxwood, holly, or yew) along the front of the house", "Add 3-5 flowering perennials (hydrangeas, lavender, or black-eyed Susans) for color", "Spread 3-4 inches of fresh hardwood mulch across all planting beds", "Install black aluminum landscape edging to define bed borders", "Plant seasonal annuals in pots or window boxes near the entryway", "Trim and shape any existing mature shrubs or trees"], estimatedCost: { low: 2000, high: 5000 }, potentialROI: 120, costBasis: "Foundation shrubs and perennials ($800-$2,000), mulch and edging ($400-$1,000), seasonal color plantings ($200-$500), design and installation labor ($600-$1,500).", valueRationale: "Michigan State University research shows professional landscaping adds 5-11% to perceived home value. The 120% ROI reflects the moderate cost recovery rate while accounting for the property's enhanced marketability.", priority: "medium", timeframe: "2-3 days" },
      { title: "Exterior Lighting", description: "Install modern outdoor sconces, path lighting, and accent fixtures. Proper exterior lighting improves safety, extends usable outdoor hours, and gives the property a polished, upscale appearance.", specificChanges: ["Mount two modern LED coach-style sconces flanking the front door", "Install 6-8 low-voltage LED path lights along the front walkway", "Add 2-3 LED uplights at the base of trees or architectural features", "Replace garage light with dusk-to-dawn LED fixture", "Install illuminated address plaque or backlit house numbers"], estimatedCost: { low: 500, high: 1500 }, potentialROI: 180, costBasis: "LED wall sconces ($100-$300 each, 2-3 units), path lights ($15-$40 each, 6-10 units), installation labor including wiring ($200-$500).", valueRationale: "Low-cost exterior lighting improvements have an outsized impact on perceived value. Evening and twilight showings benefit enormously. The 180% ROI accounts for the low cost base with meaningful aesthetic improvement.", priority: "medium", timeframe: "1 day" },
    ],
    estimatedValueImpact: 18500,
  },
  "kitchen": {
    overallScore: 55,
    condition: "fair",
    issues: ["Outdated cabinets", "Old countertops", "Basic appliances", "Poor lighting"],
    improvements: [
      { title: "Cabinet Refacing", description: "Replace cabinet doors and hardware with modern shaker-style fronts in white or gray. Cabinet refacing delivers the visual impact of a full remodel at a fraction of the cost, transforming the kitchen's entire appearance.", specificChanges: ["Remove all existing cabinet doors and drawer fronts", "Sand and clean cabinet boxes, fill any holes or dents with wood filler", "Install shaker-style replacement doors in white or soft gray finish", "Replace all hinges with soft-close concealed European hinges", "Install brushed nickel bar pulls on all doors and drawers", "Touch up cabinet boxes with matching paint or peel-and-stick veneer"], estimatedCost: { low: 4000, high: 8000 }, potentialROI: 175, costBasis: "Shaker-style replacement doors ($50-$150 per door for 15-25 doors), new handles and pulls ($5-$20 each), professional installation labor at $40-$60/hr for 2-3 days.", valueRationale: "Kitchen updates are the #1 factor in home buyer decisions per NAR surveys. Cabinet refacing recovers 75-85% of cost directly, with additional indirect value from faster sale. 175% ROI reflects the combined impact.", priority: "high", timeframe: "3-5 days" },
      { title: "Quartz Countertops", description: "Install durable quartz countertops in a neutral pattern, including a new undermount sink and faucet. Quartz is the most requested countertop material by buyers, signaling a modern, move-in ready kitchen.", specificChanges: ["Remove existing countertops and disconnect sink plumbing", "Template new countertop layout including sink cutout and edge profile", "Fabricate and install 3cm quartz slab in Calacatta or Carrara pattern", "Mount stainless steel undermount sink with mounting clips and sealant", "Install single-handle pull-down kitchen faucet in brushed nickel", "Apply silicone sealant along backsplash edge and wall joints"], estimatedCost: { low: 3500, high: 6000 }, potentialROI: 160, costBasis: "Quartz slab material at $50-$100/sqft for approximately 40 sqft of counter space, undermount sink ($200-$400), faucet ($150-$350), templating and professional installation ($500-$1,000).", valueRationale: "Quartz countertops are the #1 desired kitchen feature per Houzz surveys. Properties with updated countertops sell 5-10 days faster. The 160% ROI factors in direct appraisal value increase plus reduced time on market.", priority: "high", timeframe: "2-3 days" },
      { title: "Stainless Appliances", description: "Upgrade to matching stainless steel appliances for a cohesive, modern look. Mismatched or dated appliances are one of the most common buyer complaints during showings.", specificChanges: ["Disconnect and remove all existing kitchen appliances", "Install stainless steel French door refrigerator with ice and water dispenser", "Install gas or electric freestanding range with convection oven", "Install built-in stainless steel dishwasher with quiet operation rating", "Install over-the-range stainless steel microwave with vented hood", "Verify all electrical, gas, and water connections meet local code"], estimatedCost: { low: 3000, high: 7000 }, potentialROI: 130, costBasis: "Stainless steel appliance package: refrigerator ($800-$2,000), range/oven ($500-$1,500), dishwasher ($400-$800), microwave ($200-$400), delivery and haul-away ($100-$300).", valueRationale: "Matching stainless appliances are expected by buyers in the mid-range and above. While appliance value depreciates, the 130% ROI reflects elimination of a key buyer objection that would otherwise reduce offers.", priority: "medium", timeframe: "1 day" },
      { title: "Under-Cabinet Lighting", description: "Add LED under-cabinet task lighting and update overhead fixtures. Good lighting makes kitchens appear larger and more functional, a low-cost change with high visual impact.", specificChanges: ["Install LED light strips under all upper cabinets using adhesive aluminum channels", "Wire all under-cabinet lights to a single wall switch or dimmer control", "Replace overhead fluorescent fixture with recessed LED can lights", "Install pendant lights over island or breakfast bar if applicable", "Add LED puck lights inside glass-front cabinets for display lighting"], estimatedCost: { low: 500, high: 1200 }, potentialROI: 220, costBasis: "LED under-cabinet light strips ($100-$300), updated overhead pendant or recessed fixtures ($150-$400), electrical work and installation ($200-$500).", valueRationale: "Lighting updates have among the highest ROIs due to very low cost with dramatic visual improvement. The 220% ROI reflects the fact that properly lit kitchens photograph better and show better, directly impacting offers.", priority: "medium", timeframe: "1 day" },
      { title: "Tile Backsplash", description: "Install a modern subway or mosaic tile backsplash. A backsplash ties the kitchen design together and signals attention to detail that buyers associate with a well-maintained home.", specificChanges: ["Remove existing backsplash material or prep bare drywall surface", "Apply thinset mortar to wall in manageable working sections", "Install 3x6 white ceramic subway tile in classic brick-lay pattern from countertop to upper cabinets", "Apply unsanded grout in light gray between all tile joints", "Seal all grout lines with penetrating grout sealer", "Caulk perimeter edges where tile meets countertop, cabinets, and wall ends"], estimatedCost: { low: 800, high: 2000 }, potentialROI: 190, costBasis: "Subway or mosaic tile at $5-$15/sqft for approximately 30 sqft, thinset and grout ($50-$100), installation labor ($300-$800).", valueRationale: "Backsplash installation is one of the most efficient kitchen upgrades. The 190% ROI is driven by the low material cost combined with the finished, designer look it provides.", priority: "low", timeframe: "1-2 days" },
    ],
    estimatedValueImpact: 35000,
  },
  "bathroom": {
    overallScore: 62,
    condition: "fair",
    issues: ["Dated vanity", "Old fixtures", "Basic tile", "Inadequate storage"],
    improvements: [
      { title: "New Vanity", description: "Install a modern floating vanity with quartz top and undermount sink. The vanity is the centerpiece of any bathroom and an updated one instantly modernizes the entire space.", specificChanges: ["Remove old vanity unit and disconnect all plumbing connections", "Repair and prep wall surface where old vanity was mounted", "Install 36-inch or 48-inch floating vanity with soft-close drawers", "Mount quartz countertop with 4-inch integrated backsplash", "Install undermount rectangular porcelain sink with mounting clips", "Connect brushed nickel widespread faucet with ceramic disc valves and pop-up drain", "Add LED-backlit rectangular mirror above vanity"], estimatedCost: { low: 1500, high: 3000 }, potentialROI: 165, costBasis: "Floating vanity with quartz top ($600-$1,500), undermount sink ($150-$400), faucet ($100-$300), plumbing connections and installation ($300-$800).", valueRationale: "Bathroom updates recover 60-70% of cost per NARI, with vanity replacement being the highest-impact single change. The 165% ROI accounts for the visual transformation relative to moderate cost.", priority: "high", timeframe: "1-2 days" },
      { title: "Updated Fixtures", description: "Replace faucets, showerhead, and hardware with brushed nickel or matte black finishes. Coordinated hardware creates a cohesive, updated look throughout the bathroom.", specificChanges: ["Replace sink faucet with single-handle brushed nickel or matte black model", "Install rain showerhead with handheld combo on adjustable slide bar", "Swap out towel bars and rings with matching coordinated set in same finish", "Replace toilet flush handle with matching finish lever", "Install new matching toilet paper holder and robe hooks on wall", "Update cabinet knobs or pulls with coordinating brushed nickel hardware"], estimatedCost: { low: 400, high: 900 }, potentialROI: 200, costBasis: "Faucet ($80-$250), rain showerhead ($60-$200), towel bars and hooks ($40-$100), toilet handle and hinges ($20-$50), installation labor ($100-$300).", valueRationale: "Fixture updates are among the highest-ROI bathroom changes due to extremely low cost with visible impact. The 200% ROI reflects that coordinated modern hardware eliminates the dated look buyers penalize.", priority: "high", timeframe: "1 day" },
      { title: "Tile Refresh", description: "Re-grout existing tile or install new floor tile with a tile accent wall. Updated tile transforms the bathroom from dated to contemporary at moderate cost.", specificChanges: ["Remove existing floor tile and inspect subfloor for water damage", "Install cement backer board over subfloor for proper tile substrate", "Lay 12x24 porcelain floor tile in herringbone or staggered offset pattern", "Install coordinating accent tile strip or niche surround in shower area", "Apply epoxy grout in coordinating color for stain resistance and durability", "Seal all grout lines and install new tile base trim at floor edges"], estimatedCost: { low: 1000, high: 3500 }, potentialROI: 145, costBasis: "Floor tile at $3-$10/sqft for 40-60 sqft, accent wall tile at $5-$15/sqft for 20-30 sqft, thinset, grout and supplies ($100-$200), installation labor ($500-$1,500).", valueRationale: "Tile work has a moderate ROI of 145% because the cost is higher but the transformation is significant. Updated tile eliminates a common buyer objection about aging bathrooms.", priority: "medium", timeframe: "2-3 days" },
      { title: "Mirror & Lighting", description: "Install a frameless mirror with integrated LED lighting. Modern bathroom lighting makes the space feel larger and more luxurious while improving daily functionality.", specificChanges: ["Remove existing vanity mirror and outdated light fixture", "Install frameless LED-backlit mirror with built-in anti-fog feature", "Mount modern 3-light vanity bar fixture above mirror in brushed nickel", "Add dimmer switch on vanity lighting circuit for adjustable ambiance", "Install recessed LED can light in shower area with waterproof trim ring"], estimatedCost: { low: 300, high: 800 }, potentialROI: 210, costBasis: "LED-integrated frameless mirror ($150-$400), vanity light fixture ($80-$200), electrical connections and installation ($70-$200).", valueRationale: "Low-cost, high-impact improvement. The 210% ROI reflects how modern lighting and mirrors transform bathroom photography and showing experience at minimal expense.", priority: "medium", timeframe: "1 day" },
    ],
    estimatedValueImpact: 12000,
  },
  "roof": {
    overallScore: 72,
    condition: "good",
    issues: ["Minor wear visible", "Some debris accumulation", "Gutters need cleaning"],
    improvements: [
      { title: "Professional Cleaning", description: "Power wash roof and clean gutters to remove moss and debris. A clean roof signals proper maintenance and prevents buyers from worrying about hidden damage.", specificChanges: ["Set up roof safety equipment and lay protective drop cloths below work areas", "Soft-wash entire roof surface with contractor-grade algae and moss removal solution", "Clear all debris, leaves, and branches from roof valleys and edges", "Flush and clean all gutters and downspouts to ensure free flow", "Check and clear all downspout drains and extensions at ground level", "Apply zinc or copper moss prevention strips along the ridgeline"], estimatedCost: { low: 300, high: 600 }, potentialROI: 180, costBasis: "Professional roof power washing ($200-$400), gutter cleaning ($100-$200). Costs based on average single-family roof of 1,500-2,000 sqft.", valueRationale: "A dirty roof creates disproportionate buyer concern about deferred maintenance. The 180% ROI reflects the very low cost against the elimination of a major visual red flag during inspections.", priority: "high", timeframe: "1 day" },
      { title: "Gutter Guards", description: "Install gutter guards to prevent debris buildup and reduce ongoing maintenance costs. This is a selling point that reduces buyer concerns about long-term upkeep.", specificChanges: ["Remove existing gutter screens or mesh covers if present", "Clean and flush all gutters down to bare surface", "Install micro-mesh stainless steel gutter guard system along all gutter runs", "Secure guards with stainless steel self-tapping screws into front gutter lip", "Verify proper water flow and drainage at all downspout connections", "Re-attach any loose gutter hangers or fascia brackets along the roofline"], estimatedCost: { low: 800, high: 1800 }, potentialROI: 120, costBasis: "Gutter guard material at $5-$10/linear foot for approximately 150 linear feet of gutters, professional installation labor ($300-$600).", valueRationale: "Gutter guards are valued by buyers as a maintenance-reducing upgrade. The 120% ROI is conservative, reflecting steady but moderate value impact across the property's marketability.", priority: "medium", timeframe: "1 day" },
      { title: "Seal & Repair", description: "Seal minor cracks and repair damaged shingles to extend roof life. Proactive repairs prevent small issues from becoming deal-breaking problems during buyer inspections.", specificChanges: ["Inspect all roof surfaces for cracked, curled, or missing shingles", "Replace damaged shingles with color-matched architectural shingles and roofing nails", "Apply polyurethane roofing sealant to all exposed nail heads and hairline cracks", "Re-seal flashing around chimney, vents, and skylights with roofing cement", "Replace cracked or deteriorated rubber pipe boot covers with new units", "Inspect and re-seal ridge cap shingles along all roof peaks"], estimatedCost: { low: 500, high: 1500 }, potentialROI: 150, costBasis: "Roofing sealant and flashing repair ($100-$300), shingle replacement ($200-$500 for minor areas), professional roofer labor at $50-$75/hr for 3-6 hours.", valueRationale: "Roof concerns are the #1 deal-killer in home inspections. The 150% ROI reflects that even minor repairs can save a sale worth thousands more than the repair cost.", priority: "medium", timeframe: "1-2 days" },
    ],
    estimatedValueImpact: 5000,
  },
  "living-room": {
    overallScore: 64,
    condition: "fair",
    issues: ["Worn carpet or flooring", "Dated light fixtures", "Plain walls need refresh"],
    improvements: [
      { title: "New Flooring", description: "Install hardwood or luxury vinyl plank for a modern, durable finish. Hard surface flooring is the most requested feature in buyer surveys and worn carpet is a top showing turn-off.", specificChanges: ["Remove existing carpet, padding, and tack strips down to subfloor", "Level subfloor with self-leveling compound and secure any squeaky areas", "Install moisture barrier underlayment across entire floor surface", "Install luxury vinyl plank in medium-tone oak or walnut finish using click-lock system", "Cut and fit planks precisely around doorways, vents, and corners", "Install matching baseboards and quarter-round molding at all floor edges", "Add transition strips at doorways to adjacent rooms"], estimatedCost: { low: 3000, high: 8000 }, potentialROI: 160, costBasis: "Luxury vinyl plank at $3-$7/sqft material cost for approximately 400-600 sqft, installation at $2-$4/sqft, subfloor prep ($200-$500), transitions and trim ($200-$400).", valueRationale: "NAR reports that hardwood/LVP floors recover 100-150% of cost. Homes with hard surface flooring sell 10-15% faster. The 160% ROI accounts for both direct value and reduced days on market.", priority: "high", timeframe: "2-4 days" },
      { title: "Fresh Paint", description: "Repaint with modern neutral tones to brighten and update the space. Fresh paint is the single most cost-effective improvement, making rooms feel cleaner, larger, and more inviting.", specificChanges: ["Move furniture to center of room and lay drop cloths on all surfaces", "Patch all nail holes, dents, and cracks with lightweight spackle", "Sand all patched areas smooth and wipe walls clean with tack cloth", "Apply one coat of primer to any stained or previously dark-colored areas", "Roll two coats of eggshell-finish paint in Accessible Beige or Repose Gray (Sherwin-Williams)", "Cut in all edges at ceiling line, trim, and corners with angled brush", "Paint all trim and baseboards in semi-gloss white for a crisp contrast"], estimatedCost: { low: 500, high: 1500 }, potentialROI: 250, costBasis: "Paint at $30-$50/gallon (3-5 gallons for a typical living room), primer ($20-$30/gallon), supplies ($50-$100), labor at $35-$50/hr for 8-16 hours, or DIY to reduce cost.", valueRationale: "Interior painting is consistently the highest-ROI home improvement at 250%+. Fresh neutral paint appeals to the broadest buyer pool and photographs dramatically better for online listings.", priority: "high", timeframe: "1-2 days" },
      { title: "Updated Lighting", description: "Replace dated fixtures with modern recessed or track lighting. Good lighting transforms how a space is perceived, making rooms appear larger and more inviting.", specificChanges: ["Remove existing dated ceiling fixture or ceiling fan", "Install 4-6 evenly spaced recessed LED can lights across the ceiling", "Add a statement pendant or semi-flush mount fixture as a central focal point", "Install dimmer switches on all new lighting circuits for adjustable ambiance", "Add LED accent strip lighting behind floating shelves or in tray ceiling if present"], estimatedCost: { low: 400, high: 1200 }, potentialROI: 200, costBasis: "Recessed or track lighting fixtures ($50-$150 each, 4-6 units), dimmer switches ($20-$40 each), electrical installation ($200-$500).", valueRationale: "Updated lighting has a 200% ROI because the low cost produces dramatic visual improvement. Properly lit spaces photograph better for listings and feel more premium during showings.", priority: "medium", timeframe: "1 day" },
    ],
    estimatedValueImpact: 15000,
  },
  "bedroom": {
    overallScore: 70,
    condition: "good",
    issues: ["Basic flooring", "Insufficient closet space", "Standard fixtures"],
    improvements: [
      { title: "Closet System", description: "Install a custom closet organizer system to maximize storage. Adequate, organized closet space is a top buyer priority, especially in master bedrooms.", specificChanges: ["Remove existing wire shelving and patch all wall anchor holes", "Measure closet interior and plan layout for double-hang rods, shelves, and drawers", "Install floor-based or wall-mounted closet organizer system in white melamine finish", "Add double-hang rods on one side for shirts, jackets, and pants", "Install adjustable shelving on opposite side for folded items and shoes", "Add pull-out fabric or wire drawers for accessories and small items", "Mount battery-operated or hardwired LED closet light with motion sensor"], estimatedCost: { low: 800, high: 2500 }, potentialROI: 140, costBasis: "Closet organization system components ($300-$1,200), shelving and rods ($100-$400), professional installation ($200-$600), or DIY with kit systems.", valueRationale: "Closet space is rated as a top-5 feature by home buyers. The 140% ROI reflects moderate cost recovery at resale, with additional value from making the property more competitive against similar listings.", priority: "medium", timeframe: "1 day" },
      { title: "Fresh Paint & Trim", description: "Repaint walls and update baseboards and crown molding. Clean, neutral walls with sharp trim create a finished look that photographs well and appeals to buyers.", specificChanges: ["Fill all nail holes and repair any wall dings or dents with lightweight spackle", "Sand patched areas and lightly scuff walls for paint adhesion", "Apply two coats of eggshell-finish paint in Pale Oak or Classic Gray (Benjamin Moore)", "Install primed MDF crown molding along the entire ceiling perimeter", "Replace any damaged or scuffed baseboards with matching profile material", "Paint all trim, baseboards, and crown molding in semi-gloss white"], estimatedCost: { low: 400, high: 1000 }, potentialROI: 200, costBasis: "Interior paint ($30-$50/gallon, 2-3 gallons), trim paint ($25-$40/gallon), crown molding if adding ($3-$8/linear ft for 50-60 ft), installation labor ($200-$500).", valueRationale: "Fresh paint with updated trim is a low-cost improvement that signals move-in readiness. The 200% ROI comes from the strong cost-to-perception ratio that influences buyer willingness to pay.", priority: "medium", timeframe: "1-2 days" },
      { title: "Upgraded Flooring", description: "Install new carpet or hardwood flooring. Bedroom flooring affects comfort perception and stained or worn floor covering immediately signals neglect to buyers.", specificChanges: ["Remove existing carpet, padding, and all tack strips from the room", "Inspect subfloor for damage and secure any squeaky spots with screws", "Install premium 8-pound density carpet padding for plush underfoot comfort", "Install stain-resistant nylon carpet in neutral tone with soft cut-pile texture", "Stretch and seam carpet professionally for a smooth, wrinkle-free finish", "Install new carpet transition strip at bedroom doorway"], estimatedCost: { low: 1500, high: 4000 }, potentialROI: 130, costBasis: "New carpet at $3-$6/sqft or hardwood at $6-$12/sqft for 150-250 sqft bedroom, carpet padding ($0.50-$1/sqft), installation labor ($1-$3/sqft).", valueRationale: "Bedroom flooring has a moderate 130% ROI. While not as impactful as kitchen or bath updates, fresh flooring removes a significant buyer objection and supports the home's overall condition narrative.", priority: "low", timeframe: "1-2 days" },
    ],
    estimatedValueImpact: 8000,
  },
  "default": {
    overallScore: 65,
    condition: "fair",
    issues: ["General wear and tear", "Dated finishes", "Deferred maintenance"],
    improvements: [
      { title: "Deep Cleaning & Staging", description: "Professional deep cleaning and staging to present the space at its best. Staging helps buyers envision themselves living in the property and is proven to increase offers.", specificChanges: ["Deep clean all flooring including carpet extraction or hard surface polishing", "Wash all windows inside and out including tracks and sills", "Clean all light fixtures, ceiling fans, and HVAC vent covers", "Declutter and remove all personal items and excess furniture from every room", "Arrange remaining furniture to maximize perceived space and traffic flow", "Add fresh towels, coordinated throw pillows, and simple neutral decor accents for staging"], estimatedCost: { low: 200, high: 500 }, potentialROI: 300, costBasis: "Professional deep cleaning ($150-$300), basic staging consultation ($50-$200). Costs are minimal relative to impact.", valueRationale: "NAR reports staged homes sell for 1-5% more than unstaged homes. The 300% ROI reflects the extremely low cost base with meaningful impact on buyer perception and offer amounts.", priority: "high", timeframe: "1 day" },
      { title: "Fresh Paint", description: "Apply fresh paint in modern neutral tones throughout. This is the single highest-ROI improvement available, transforming the look and feel of any space at minimal cost.", specificChanges: ["Patch all nail holes, dents, and hairline cracks in walls and ceilings", "Sand all patched areas flush and wipe surfaces clean with damp cloth", "Apply bonding primer to any stained, dark-colored, or heavily repaired areas", "Roll two coats of eggshell-finish paint in a warm neutral tone throughout all rooms", "Paint all trim, doors, and baseboards in semi-gloss bright white", "Touch up any scuffs or marks on door frames and window casings"], estimatedCost: { low: 500, high: 1500 }, potentialROI: 250, costBasis: "Interior paint at $30-$50/gallon (4-8 gallons depending on area), primer, supplies, and labor at $35-$50/hr. Total includes prep, two coats, and cleanup.", valueRationale: "Painting consistently delivers 250%+ ROI per industry studies. Fresh neutral paint appeals to the broadest buyer pool, photographs better for listings, and signals a well-maintained property.", priority: "high", timeframe: "1-2 days" },
      { title: "Update Fixtures", description: "Replace dated light fixtures and hardware with modern alternatives. Small hardware updates create a cohesive, contemporary look throughout the space.", specificChanges: ["Remove all outdated ceiling lights, sconces, and fan fixtures", "Install modern semi-flush mount or recessed LED fixtures in each room", "Replace all interior door knobs with matching satin nickel lever-style handles", "Swap out all light switch plates and outlet covers with white decorator-style plates", "Update cabinet pulls in kitchen and bath with brushed nickel bar-style hardware"], estimatedCost: { low: 300, high: 800 }, potentialROI: 200, costBasis: "Modern light fixtures ($50-$150 each, 2-4 units), cabinet/door hardware ($5-$15 each), installation labor ($100-$300).", valueRationale: "Fixture updates deliver 200% ROI because the very low cost produces a visible modernization. Updated hardware photographs well and eliminates the dated look buyers penalize.", priority: "medium", timeframe: "1 day" },
    ],
    estimatedValueImpact: 8000,
  },
};

export async function POST(request: NextRequest) {
  try {
    // Allow both NextAuth sessions and demo mode (no session)
    // AI analysis doesn't require user-specific DB data

    const body = await request.json();
    const { imageUrl, imageBase64, area } = body;

    if (!imageUrl && !imageBase64) {
      return NextResponse.json({ error: "Image URL or base64 data is required" }, { status: 400 });
    }

    const areaLabel = area || "property";

    // Try OpenAI Vision analysis
    if (process.env.OPENAI_API_KEY) {
      try {
        const imgInput = imageBase64
          ? `data:image/jpeg;base64,${imageBase64}`
          : imageUrl;

        const analysis = await analyzeImprovementsFromImage(imgInput, areaLabel);
        return NextResponse.json({ success: true, ...analysis, source: "openai" });
      } catch (aiError) {
        console.error("OpenAI improvements analysis failed, using fallback:", aiError);
      }
    }

    // Fallback to pre-built analysis
    const fallback = FALLBACK_ANALYSES[area] || FALLBACK_ANALYSES["default"];
    return NextResponse.json({ success: true, ...fallback, source: "fallback" });
  } catch (error) {
    console.error("Error in improvements API:", error);
    return NextResponse.json({ error: "Failed to analyze improvements" }, { status: 500 });
  }
}
